### ISSUE TITLE
Failed to install from Cordova CLI: LibRecognizr.aar not found

### ISSUE THREAD

**Issue by andreszs** [PDF417/pdf417-phonegap#22]
I'm getting this error when trying to install the plugin via Cordova CLI:

D:\PhoneGap\test>cordova plugin add ..\pdf417-phonegap-master\Pdf417
Installing "mobi.pdf417.Pdf417Scanner" for android
Error during processing of action! Attempting to revert...
Failed to install 'mobi.pdf417.Pdf417Scanner':Error: Uh oh!
"D:\PhoneGap\test\plugins\mobi.pdf417.Pdf417Scanner\src\android\pdf417-android\LibRecognizer.aar" not found!
    at Object.module.exports.common.copyFile (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\common.js:38:40)
    at module.exports.resource-file.install (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:110:20)
    at C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:653:27
    at Object.ActionStack.process (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\platforms\PlatformApiPoly.js:259:20)
    at handleInstall (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:603:6)
    at C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:382:28
    at _fulfilled (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Andres\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)
Error: Uh oh!
"D:\PhoneGap\test\plugins\mobi.pdf417.Pdf417Scanner\src\android\pdf417-android\LibRecognizer.aar" not found!

Is there any other way to install it correctly? Thanks.

**Comment by DoDoENT** [comment]
Hi!

After cloning the repository, have you [cloned submodules](https://github.com/PDF417/pdf417-phonegap#submodules)?

**Comment by DoDoENT** [comment]
Hi @andreszs,

is the issue resolved for you? Can we close it?

**Comment by andreszs** [comment]
Thanks, it is solved, the submodule clonning process was failing for another reason and I fixed that already.
