### ISSUE TITLE
Error alert asking for License Key even after adding a license key to it. 

### ISSUE THREAD

**Issue by SaurabhS-GWU** [PDF417/pdf417-phonegap#26]
I am trying to add the plugin to my ionic application with android. 
I have used the exact code as the sample app in the project and generated my new license key. 
I have added the newly generated license key in the app and it gives a message saying invalid license key.

**Comment by DoDoENT** [comment]
Hi!

Which package name are you using? Which platform (iOS or Android) are you using? Can you attach log that is outputted before message saying invalid licence key? (on Android, this is ADB logcat, on iOS it is debug log in Xcode).

**Comment by SaurabhS-GWU** [comment]
Before pressing scan button I get this message: validate_display:255 error 3008 (EGL_BAD_DISPLAY) 
Once I click the scan button I see the following message:

04-10 09:34:53.842 28195-28195/com.ionicframework.ageverify468657 E/Pdf417ScanActivity.java:337@main: INVALID LICENCE KEY
                                                                                                      com.microblink.recognition.InvalidLicenceKeyException: Failed to validate licence key. Reason: Either license key or android context is null!
                                                                                                          at com.microblink.view.recognition.RecognizerView.setLicenseKey(line:744)
                                                                                                          at com.microblink.activity.BaseScanActivity.onCreate(line:332)
                                                                                                          at android.app.Activity.performCreate(Activity.java:5990)
                                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:211)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
04-10 09:34:54.056 28195-28195/com.ionicframework.ageverify468657 E/RecognizerView.java:317@main: Failed to validate licence key. Reason: Either license key or android context is null!
04-10 09:34:54.059 28195-28195/com.ionicframework.ageverify468657 E/Pdf417ScanActivity.java:988@main: Not supported reason: Invalid license key! Please check ADB error log for more details.
04-10 09:34:54.771 28195-28195/com.ionicframework.ageverify468657 E/Pdf417ScanActivity.java:337@main: INVALID LICENCE KEY
                                                                                                      com.microblink.recognition.InvalidLicenceKeyException: Failed to validate licence key. Reason: Either license key or android context is null!
                                                                                                          at com.microblink.view.recognition.RecognizerView.setLicenseKey(line:744)
                                                                                                          at com.microblink.activity.BaseScanActivity.onCreate(line:332)
                                                                                                          at android.app.Activity.performCreate(Activity.java:5990)
                                                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2332)
                                                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                          at android.os.Looper.loop(Looper.java:211)
                                                                                                          at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                                                          at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
04-10 09:34:54.806 28195-28195/com.ionicframework.ageverify468657 E/RecognizerView.java:317@main: Failed to validate licence key. Reason: Either license key or android context is null!
04-10 09:34:54.808 28195-28195/com.ionicframework.ageverify468657 E/Pdf417ScanActivity.java:988@main: Not supported reason: Invalid license key! Please check ADB error log for more details.

**Comment by DoDoENT** [comment]
> E/RecognizerView.java:317@main: Failed to validate licence key. Reason: Either license key or android context is null!

This means that you didn't set the licence key, i.e. you set the `null` value or empty string.

**Comment by SaurabhS-GWU** [comment]
But the demo app says we can use null for the sample. 
I have also tried setting the License Key provided by Microblink but still get the same error.

**Comment by DoDoENT** [comment]
> But the demo app says we can use null for the sample.
Can you please quote where demo app says that? Some old versions used to work without licence key, but all versions from last two years require at least trial licence key.

> I have also tried setting the License Key provided by Microblink but still get the same error.

After settings the license key, you do not get the same error, because same error means that licence key is not set. You probably get the different error: can you send the stack trace and/or ADB log of the error you get after setting correct license key. Please note that license key is bound to [application ID](https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/applicationid-vs-packagename) of your app - you cannot use license key created for different application ID.

**Comment by SaurabhS-GWU** [comment]
I created a  new application by specifying the path name during creation. That solved the problem. 
Now I am trying to get all the fields from a drivers license. Can you tell me how to go about that?

**Comment by DoDoENT** [comment]
All possible DL element keys with documentation are listed [here](https://github.com/PDF417/pdf417-phonegap/blob/master/usdl_keys.js).

**Comment by SaurabhS-GWU** [comment]
Thanks a lot. Got a solution to my questions.
